CREATE TABLE IF NOT EXISTS users
(
    id UUID PRIMARY KEY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,

    email VARCHAR(255) NOT NULL UNIQUE
);