// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package application

import (
	"github.com/gin-gonic/gin"
	"github.com/zhurak-v/techpassport/auth-service/src/infrastructure/database"
	"github.com/zhurak-v/techpassport/auth-service/src/infrastructure/repository"
)

// Injectors from wire.go:

func InitApplication() (*gin.Engine, error) {
	db := database.InitDatabase()
	iRoleRepositoryContract := repository.NewRoleRepository(db)
	iMigrations := database.NewMigration()
	engine := GinApplication(iRoleRepositoryContract, iMigrations)
	return engine, nil
}
